config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :newsvilles do
    resources :comments
  end
  
  root to: 'pages#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :newsville
end

app/models/newsville.rb
class Newsville < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :newsvilles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # def google_news
  #   require 'open-uri'
  #   page = Nokogiri::HTML(open("https://news.google.com/news"))
  #   render text: page
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json

  # GET /comments/new
  def new
    @comment = Comment.new
  end


  # POST /comments
  # POST /comments.json
  def create
    @newsville = Newsville.find(params[:newsville_id])
    @comment = @newsville.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @newsville, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:newsville_id, :body, :user_id)
    end
end

app/controllers/newsvilles_controller.rb
class NewsvillesController < ApplicationController
  before_action :set_newsville, only: [:show, :edit, :update, :destroy]

  # GET /newsvilles
  # GET /newsvilles.json
  def index
    @newsvilles = Newsville.all
  end

  # GET /newsvilles/1
  # GET /newsvilles/1.json
  def show
  end

  # GET /newsvilles/new
  def new
    @newsville = Newsville.new
  end

  # GET /newsvilles/1/edit
  def edit
  end

  # POST /newsvilles
  # POST /newsvilles.json
  def create
    @newsville = Newsville.new(newsville_params)

    respond_to do |format|
      if @newsville.save
        format.html { redirect_to @newsville, notice: 'Newsville was successfully created.' }
        format.json { render :show, status: :created, location: @newsville }
      else
        format.html { render :new }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newsvilles/1
  # PATCH/PUT /newsvilles/1.json
  def update
    respond_to do |format|
      if @newsville.update(newsville_params)
        format.html { redirect_to @newsville, notice: 'Newsville was successfully updated.' }
        format.json { render :show, status: :ok, location: @newsville }
      else
        format.html { render :edit }
        format.json { render json: @newsville.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newsvilles/1
  # DELETE /newsvilles/1.json
  def destroy
    @newsville.destroy
    respond_to do |format|
      format.html { redirect_to newsvilles_url, notice: 'Newsville was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newsville
      @newsville = Newsville.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newsville_params
      params.require(:newsville).permit(:title_url, :title, :body, :time, :image_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation,
      :username,
      :image,
      :url
      )
  end

  def account_update_params
    params.require(:user).permit(
      :email, 
      :password, 
      :password_confirmation, 
      :current_password,
      :username,
      :image,
      :url
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/newsvilles_helper.rb
module NewsvillesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<div class="col-md-12">
  <div class="caption-full">
    <h4 class="pull-right"> Was posted <%= time_ago_in_words(comment.created_at) %> ago</h4>
    <h4>Comment by <%= comment.user.username %> </h4>
    
    <p><%= comment.body %></p>
    </div>
</div>  

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :newsville_id %>
    <%= f.input :body %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Newsville</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.newsville_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Newsville:</strong>
  <%= @comment.newsville_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_alert.html.erb
<% if notice || alert %>
    <div class="alert <%= notice ? "alert-info" : "" %><%= alert ? "alert-danger" : "" %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <div >
            <% if notice %>
                <%= notice %>
            <% elsif alert %>
                <%= alert %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer>
    <div class="row">
      <div class="col-lg-12">
          <p>Copyright © Your Website 2014</p>
        </div>
      </div>
              <!-- /.row -->
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        <% if current_user %>
        <li><%= link_to "Newsvilles", newsvilles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username if current_user %> <span class="caret"></span></a>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alert' %>


<div class="container">
  <%= yield %>
</div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/newsvilles/_form.html.erb
<%= simple_form_for(@newsville) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title_url %>
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :time %>
    <%= f.input :image_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/newsvilles/edit.html.erb
<h1>Editing Newsville</h1>

<%= render 'form' %>

<%= link_to 'Show', @newsville %> |
<%= link_to 'Back', newsvilles_path %>

app/views/newsvilles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Newsville</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Original Story</th>
      <th>Title</th>
      <th>Summary</th>
      <th>Story Posted At </th>
      <th>Story Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newsvilles.each do |newsville| %>
      <tr>
        <td><%= link_to "Original Story", newsville.title_url, :target => "_" %></td>
        <td><%= newsville.title %></td>
        <td><%= newsville.body %></td>
        <td><%= newsville.time %></td>
        <% if newsville.image_url.present? %>
          <td><%= image_tag newsville.image_url %></td>
        <% else %>
          <td><%= image_tag 'nia.jpeg' %></td>
        <% end %>
        <td><%= link_to 'Show', newsville, class: "btn btn-success btn-xs" %></td>
        <td><%= link_to 'Edit', edit_newsville_path(newsville), class: "btn btn-warning btn-xs" %></td>
        <td><%= link_to 'Destroy', newsville, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newsville', new_newsville_path %>

app/views/newsvilles/new.html.erb
<h1>New Newsville</h1>

<%= render 'form' %>

<%= link_to 'Back', newsvilles_path %>

app/views/newsvilles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>View:</strong>
  <%= link_to "Original Story", @newsville.title_url, :target => "_" %></td>
</p>

<p>
  <strong>Title:</strong>
  <%= @newsville.title %>
</p>

<p>
  <strong>Heading:</strong>
  <%= @newsville.body %>
</p>

<p>
  <strong>Posted:</strong>
   <%= time_ago_in_words(@newsville.created_at) %> ago
</p>

<p>
  <strong>Story Image:</strong><br />
   <% if @newsville.image_url.present? %>
    <td><%= image_tag @newsville.image_url %></td>
  <% else %>
    <td><%= image_tag 'nia.jpeg' %></td>
  <% end %>
</p>

<hr>

<%= render @newsville.comments %>
  <%= simple_form_for [@newsville, Comment.new] do |comment| %>
    <%= comment.input :body, label: false, placeholder: "Add your comments here" %>
    <%= comment.submit "Add Comment", class: "btn btn-danger" %>
    <% end %>
    <hr>
    <%= link_to 'Back to Newsville', newsvilles_path, class: "btn btn-info xs" %>

app/views/pages/index.html.erb
<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Portfolio Item
                    <small>Item Subheading</small>
                </h1>
            </div>
        </div>
        <div class="row">

            <div class="col-md-8">
                <img class="img-responsive" src="http://placehold.it/750x500" alt="">
            </div>

            <div class="col-md-4">
                <h3>Project Description</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <h3>Project Details</h3>
                <ul>
                    <li>Lorem Ipsum</li>
                    <li>Dolor Sit Amet</li>
                    <li>Consectetur</li>
                    <li>Adipiscing Elit</li>
                </ul>
            </div>

        </div>
        <div class="row">

            <div class="col-lg-12">
                <h3 class="page-header">Related Projects</h3>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
                </a>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
                </a>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
                </a>
            </div>

            <div class="col-sm-3 col-xs-6">
                <a href="#">
                    <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
                </a>
            </div>

        </div>
        
        <hr>